"let g:airline_theme=''
" let g:airline_theme='gruvbox' 
" let g:airline_theme='simple' 
" let g:airline_theme='base16'
" let g:airline_theme='light'
" let g:airline_theme='base16_solarized_light'
" let g:airline_theme='base16_solarized'
" let g:airline_theme='minimalist'

"let g:airline_theme='jellybeans'
"let g:airline_theme='alduin'
let g:airline_theme='deep_space'
